name: "Chrony Time Server"
version: "dev"
slug: "chrony-timeserver"
description: "Chrony-based time synchronization service"
url: "https://github.com/bborchers/ha-addons-chrony-timeserver/tree/main/chrony-timeserver"
arch:
  - aarch64
  - amd64
privileged:
  - SYS_TIME
init: false
options:
  servers:
    - pool.ntp.org
  nts: false
schema:
  servers:
    - str
  nts: bool
